-- AlterTable
ALTER TABLE "User" ADD COLUMN "isOwner" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "permOrders" TEXT NOT NULL DEFAULT 'all';
ALTER TABLE "User" ADD COLUMN "permProducts" TEXT NOT NULL DEFAULT 'all';
ALTER TABLE "User" ADD COLUMN "permClients" TEXT NOT NULL DEFAULT 'all';
ALTER TABLE "User" ADD COLUMN "permJournal" TEXT NOT NULL DEFAULT 'all';
ALTER TABLE "User" ADD COLUMN "permSettings" TEXT NOT NULL DEFAULT 'all';

UPDATE "User" SET "isOwner" = 1 WHERE "role" = 'optics';

ALTER TABLE "Optics" ADD COLUMN "staffLimit" INTEGER NOT NULL DEFAULT 5;
